name: Publish to PyPI and Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure valid tag
        run: |
          if [[ ! "${{ github.ref }}" =~ refs/tags/v.* ]]; then
            echo "Error: This workflow should be triggered by a version tag (v*)."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV

      - name: Extract Python version from pyproject.toml
        id: python-version
        run: |
          python_version=$(poetry run python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
          echo "python-version=${python_version}" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package
        run: poetry build

      - name: Configure Poetry for PyPI
        run: poetry config pypi-token.pypi "$POETRY_PASSWORD"
        env:
          POETRY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish to PyPI
        run: poetry publish
        continue-on-error: true

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload artifacts to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: dist/*
          file_glob: true
          release_name: ${{ github.ref_name }}
